# Use public NTP servers

server tt.pool.ntp.org iburst
# server pool.ntp.org iburst
# server time.cloudflare.com iburst

# Allow access from local network (example: 192.168.0.0/24)
allow all

#rtcsync

makestep 0.1 3

# Local stratum
local stratum 10

# Drift file
driftfile /var/lib/chrony/chrony.drift

# Log settings
logdir /var/log/chrony
log measurements statistics tracking
